/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.ScrollPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Cadidato;
import modelos.CandidatoBO;
import dao.EntrevistadorDAO;
import modelos.Entrevistador;

/**
 *
 * @author Ezeks
 */
public class ControleCandidatos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControleCandidatos
     */
    public ControleCandidatos() {
        initComponents();
        DefaultTableModel modeltable = (DefaultTableModel) tabelacandidatos.getModel();
        tabelacandidatos.setRowSorter(new TableRowSorter(modeltable));
        preencherTabela();
        
        //ESTILIZAÇÃO DOS BOTÕES
        
        /*jButton4.setFont(new Font("Ravie", 1, 18));
        jButton4.setForeground(new Color(105,105,105));
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,149,237), 3));
        
        jButton4.setRequestFocusEnabled(false);
       jButton4.setRolloverEnabled(false);
       jButton4.setMargin(new Insets(2, 1000, 2, 14));
       
       jButton5.setFont(new Font("Ravie", 1, 18));
        jButton5.setForeground(new Color(105,105,105));
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,149,237), 3));
        
        jButton5.setRequestFocusEnabled(false);
       jButton5.setRolloverEnabled(false);
       jButton5.setMargin(new Insets(2, 1000, 2, 14));
       
       jButton6.setFont(new Font("Ravie", 1, 18));
        jButton6.setForeground(new Color(105,105,105));
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,149,237), 3));
        
        jButton6.setRequestFocusEnabled(false);
       jButton6.setRolloverEnabled(false);
       jButton6.setMargin(new Insets(2, 1000, 2, 14));
        */
        
    }
    
    public void LimpaCampo(){
        this.nome.setText("");
        this.cpf.setText("");
        this.email.setText("");
        this.nascimento.setText("");
        this.telefone.setText("");
        this.genero.setText("");
        this.formacao.setText("");
        this.endereco.setText("");
        this.numero.setText("");
        this.cep.setText("");
        this.uf.setText("");
        this.pesquisa.setText("");
        this.experiencia.setText("");
    
    
    }
    
    
    public void preencherTabela(){
        
        DefaultTableModel modeltable = (DefaultTableModel) tabelacandidatos.getModel();
         modeltable.setNumRows(0);
         CandidatoBO candidatobo = new CandidatoBO();
         
         for (Cadidato candidato: candidatobo.consulta()){
             modeltable.addRow(new Object[]{
             candidato.getIdCandidato() ,candidato.getNome(), candidato.getCpf(), candidato.getEmail(), candidato.getNiversario(), candidato.getTelefone(), candidato.getGenero(),candidato.getFormacao(), candidato.getEndereco(), candidato.getNumero(), candidato.getCep(), candidato.getNumero(), candidato.getUf(), candidato.getCursos(), candidato.getEsperiecia()
             });
         }
             
    }
    
        public void preencherTabelaPesquisa(String nomePesq){
        
        DefaultTableModel modeltable = (DefaultTableModel) tabelacandidatos.getModel();
         modeltable.setNumRows(0);
         CandidatoBO candidatobo = new CandidatoBO();
         
         for (Cadidato candidato: candidatobo.pesquisaCandidato(nomePesq)){
             modeltable.addRow(new Object[]{
             candidato.getIdCandidato() ,candidato.getNome(), candidato.getCpf(), candidato.getEmail(), candidato.getNiversario(), candidato.getTelefone(), candidato.getGenero(),candidato.getFormacao(), candidato.getEndereco(), candidato.getNumero(), candidato.getCep(), candidato.getNumero(), candidato.getUf(), candidato.getCursos(), candidato.getEsperiecia()
             });
         }
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelacandidatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nascimento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        uf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        experiencia = new javax.swing.JTextField();
        pesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cep = new javax.swing.JTextField();
        formacao = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        curso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Candidate Control");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/interface3.png"))); // NOI18N

        tabelacandidatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelacandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Cpf", "Birth date", "Phone", "Genre", "Formacao", "Address", "Número", "CEP", "UF", "Courses", "Experiences"
            }
        ));
        tabelacandidatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelacandidatos.setMinimumSize(new java.awt.Dimension(80, 80));
        tabelacandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelacandidatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelacandidatos);
        if (tabelacandidatos.getColumnModel().getColumnCount() > 0) {
            tabelacandidatos.getColumnModel().getColumn(1).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(1).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(1).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(2).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(2).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(2).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(3).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(3).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(3).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(4).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabelacandidatos.getColumnModel().getColumn(4).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(5).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(5).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(5).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(6).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(6).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(6).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(8).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(8).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(8).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(9).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(9).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(9).setMaxWidth(300);
            tabelacandidatos.getColumnModel().getColumn(10).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(10).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(10).setMaxWidth(300);
            tabelacandidatos.getColumnModel().getColumn(11).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(11).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(11).setMaxWidth(300);
            tabelacandidatos.getColumnModel().getColumn(12).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(12).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(12).setMaxWidth(300);
            tabelacandidatos.getColumnModel().getColumn(13).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(13).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(13).setMaxWidth(300);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Search Candidates");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        nome.setBackground(new java.awt.Color(240, 239, 253));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phone:");

        telefone.setBackground(new java.awt.Color(240, 239, 253));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        email.setBackground(new java.awt.Color(240, 239, 253));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address:");

        endereco.setBackground(new java.awt.Color(240, 239, 253));
        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Birth date:");

        nascimento.setBackground(new java.awt.Color(240, 239, 253));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Genre:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CPF:");

        cpf.setBackground(new java.awt.Color(240, 239, 253));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Additional Information");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Courses:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Experiences:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Personal informations");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Zip Code:");

        genero.setBackground(new java.awt.Color(240, 239, 253));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Number:");

        numero.setBackground(new java.awt.Color(240, 239, 253));
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("UF:");

        uf.setBackground(new java.awt.Color(240, 239, 253));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo123.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Academic formation:");

        experiencia.setBackground(new java.awt.Color(240, 239, 253));

        pesquisa.setBackground(new java.awt.Color(240, 239, 253));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cep.setBackground(new java.awt.Color(240, 239, 253));
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });

        formacao.setBackground(new java.awt.Color(240, 239, 253));
        formacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formacaoActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Limpa Campos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        curso.setBackground(new java.awt.Color(240, 239, 253));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("List of all registered candidates");

        btnPesquisa.setBackground(new java.awt.Color(102, 102, 102));
        btnPesquisa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setText("Search");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton4))
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jLabel7)
                            .addGap(6, 6, 6)
                            .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jLabel15)
                            .addGap(23, 23, 23)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)
                            .addGap(11, 11, 11)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17)
                            .addGap(11, 11, 11)
                            .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel13)
                                    .addGap(12, 12, 12)
                                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(10, 10, 10)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(11, 11, 11)
                                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(formacao, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(590, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(formacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(374, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(240, 240, 240)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelacandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelacandidatosMouseClicked
        // TODO add your handling code here:
        //quando o o entrevistador clicar em uma linha da tabela
        int linha = this.tabelacandidatos.getSelectedRow();
        int id = (int) tabelacandidatos.getModel().getValueAt(linha, 0);
        
        String nome1 = tabelacandidatos.getModel().getValueAt(linha, 1).toString();
        String email1 = tabelacandidatos.getModel().getValueAt(linha, 2).toString();
        String cpf1 = tabelacandidatos.getModel().getValueAt(linha, 3).toString();
        String nasc = tabelacandidatos.getModel().getValueAt(linha, 4).toString();
        String tel = tabelacandidatos.getModel().getValueAt(linha, 5).toString();
        String genero2 = tabelacandidatos.getModel().getValueAt(linha, 6).toString();
        String formacao2 = tabelacandidatos.getModel().getValueAt(linha, 7).toString();
        String ender = tabelacandidatos.getModel().getValueAt(linha, 8).toString();
        String numero2 = tabelacandidatos.getModel().getValueAt(linha, 9).toString();
        String cep1 = tabelacandidatos.getModel().getValueAt(linha, 10).toString();
        
        
        
        String uf1 = tabelacandidatos.getModel().getValueAt(linha, 11).toString();
        String curso1 = tabelacandidatos.getModel().getValueAt(linha, 12).toString();
        String exp = tabelacandidatos.getModel().getValueAt(linha, 13).toString();
        //String n1 = tabelacandidatos.getModel().getValueAt(linha, 10).toString();
        
        
        this.nome.setText(nome1);
        this.cpf.setText(cpf1);
        this.email.setText(email1);
        this.nascimento.setText(nasc);
        this.telefone.setText(tel);
        this.genero.setText(genero2);
        this.formacao.setText(formacao2);
        this.endereco.setText(ender);
        this.numero.setText(numero2);
        this.cep.setText(cep1);
        this.uf.setText(uf1);
        this.pesquisa.setText(curso1);
        this.experiencia.setText(exp);
        
        System.out.println("o id da candidato é: " + id);
            
    }//GEN-LAST:event_tabelacandidatosMouseClicked

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //botao de cadastrar
        String nome1 = this.nome.getText();
        String email1 = this.email.getText();
        String cpf1 = this.cpf.getText();
        String nasc1 = this.nascimento.getText();
        String genero1 = this.genero.getText();
        String formacao1 = this.formacao.getText();
        String telefone1 = this.telefone.getText();
        String endereco1 = this.endereco.getText();
        String numero1 = this.numero.getText();
        String cep1 = this.cep.getText();
        String uf1 = this.uf.getText();
        String curso1 = this.pesquisa.getText();
        String exp1 = this.experiencia.getText();
        
        EntrevistadorDAO dao = new EntrevistadorDAO();
        
        Entrevistador a = new Entrevistador();
        
        
        //System.out.println("o id do entrevistador no arquivo controle candidato e´: " + a.getNome());
        int idEntrevistador1 = dao.getID();
        //int idEntrevistador1 = 1;
        
        Cadidato candidato = new Cadidato();
        
        candidato.setNome(nome1);
        candidato.setEmail(email1);
        candidato.setCpf(cpf1);
        candidato.setNiversario(nasc1);
        candidato.setGenero(genero1);
        candidato.setFormacao(formacao1);
        candidato.setTelefone(telefone1);
        candidato.setEndereco(endereco1);
        candidato.setNumero(numero1);
        candidato.setCep(cep1);
        candidato.setUf(uf1);
        candidato.setCursos(curso1);
        candidato.setEsperiecia(exp1);
        candidato.setIdEntrevistador(idEntrevistador1);
        
        
        CandidatoBO bo = new CandidatoBO();
        
        
        
        
        int options = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Deseja Realmente Cadastrar o Candidato?" ,"IMPORTANT", options, 3);
        if (result == JOptionPane.YES_OPTION) {
            try {
                bo.cadastrar(candidato);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Houve um erro na hora de cadastrar um candidato");
            }
            preencherTabela();
            
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "OK");
        }
        
        /*try {
            bo.cadastrar(candidato);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Houve um erro na hora de cadastrar um candidato");
        }
        preencherTabela();*/
        
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //atualizar
        int linha = this.tabelacandidatos.getSelectedRow();
        int coluna = 0;
        int Id = Integer.parseInt(tabelacandidatos.getModel().getValueAt(linha, coluna).toString());
        
        System.out.println("o valor do id  na classe controle é: " + Id);
        
        String nome3 = this.nome.getText();
        String email3 = this.email.getText();
        String cpf3 = this.cpf.getText();
        String nasc3 = this.nascimento.getText();
        String genero3 = this.genero.getText();
        String formacao3 = this.formacao.getText();
        String telefone3 = this.telefone.getText();
        String endereco3 = this.endereco.getText();
        String numero3 = this.numero.getText();
        String cep3 = this.cep.getText();
        String uf3 = this.uf.getText();
        String curso3 = this.pesquisa.getText();
        String exp3 = this.experiencia.getText();
        
        Cadidato candidato = new Cadidato();
        
        candidato.setIdCandidato(Id);
        candidato.setNome(nome3);
        candidato.setEmail(email3);
        candidato.setCpf(cpf3);
        candidato.setNiversario(nasc3);
        candidato.setGenero(genero3);
        candidato.setFormacao(formacao3);
        candidato.setTelefone(telefone3);
        candidato.setEndereco(endereco3);
        candidato.setNumero(numero3);
        candidato.setCep(cep3);
        candidato.setUf(uf3);
        candidato.setCursos(curso3);
        candidato.setEsperiecia(exp3);
        
        CandidatoBO bo = new CandidatoBO();
        
        
        try {
            bo.atualizar(candidato);
            JOptionPane.showMessageDialog(null, "Candidato atualizado com sucesso");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "erro ao atualizar o candidato");
            
        }
        preencherTabela();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //deletar
        int linha = this.tabelacandidatos.getSelectedRow();
        int coluna = 0;
        
        String value = tabelacandidatos.getModel().getValueAt(linha, coluna).toString();
        
        Cadidato candidato = new Cadidato();
        
        candidato.setIdCandidato(Integer.parseInt(value));
        
        CandidatoBO bo = new CandidatoBO();
        
        try {
            bo.deletar(candidato);
            JOptionPane.showMessageDialog(null, "Candidato excluída com sucesso");
            
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao excluir a o candidato");
        }
        preencherTabela();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void formacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formacaoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.LimpaCampo();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        preencherTabelaPesquisa(pesquisa.getText());
        
        
        
        
    }//GEN-LAST:event_btnPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField curso;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField experiencia;
    private javax.swing.JTextField formacao;
    private javax.swing.JTextField genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JTable tabelacandidatos;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
