/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import java.awt.Font;

/**
 *
 * @author Ezeks
 */
public class Questionario1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Questionario1
     */
    public Questionario1() {
        initComponents();
        
        pergunta1.setText("What is your career goal?");
        pergunta1.setBackground(new java.awt.Color(0,0,0,1));
        pergunta2.setText("Could you tell me about yourself and describe your background briefly?");
        pergunta2.setBackground(new java.awt.Color(0,0,0,1));
        pergunta3.setText("Tell me about your professional experiences (if you have any).");
        pergunta3.setBackground(new java.awt.Color(0,0,0,1));
        pergunta4.setText("What are your working hours?");
        pergunta4.setBackground(new java.awt.Color(0,0,0,1));
        
        pergunta5.setText("What is your career goal?");
        pergunta5.setBackground(new java.awt.Color(0,0,0,1));
        pergunta6.setText("Could you tell me about yourself and describe your background briefly?");
        pergunta6.setBackground(new java.awt.Color(0,0,0,1));
        pergunta7.setText("Tell me about your professional experiences (if you have any).");
        pergunta7.setBackground(new java.awt.Color(0,0,0,1));
        pergunta8.setText("What are your working hours?");
        pergunta8.setBackground(new java.awt.Color(0,0,0,1));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slide = new diu.swe.habib.JPanelSlider.JPanelSlider();
        painel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pergunta1 = new javax.swing.JTextField();
        pergunta2 = new javax.swing.JTextField();
        pergunta3 = new javax.swing.JTextField();
        pergunta4 = new javax.swing.JTextField();
        resposta1 = new javax.swing.JTextField();
        resposta2 = new javax.swing.JTextField();
        resposta3 = new javax.swing.JTextField();
        resposta4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        painel2 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pergunta5 = new javax.swing.JTextField();
        pergunta6 = new javax.swing.JTextField();
        pergunta8 = new javax.swing.JTextField();
        pergunta7 = new javax.swing.JTextField();
        resposta5 = new javax.swing.JTextField();
        resposta8 = new javax.swing.JTextField();
        resposta6 = new javax.swing.JTextField();
        resposta7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        painel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);

        painel1.setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(242, 242, 242));
        kGradientPanel1.setkStartColor(new java.awt.Color(215, 215, 215));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Questions for the Interviewed");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(15, 16, 325, 32);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(403, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jPanel4);
        jPanel4.setBounds(15, 54, 403, 3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Question 1");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(15, 79, 75, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Answer:");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(15, 120, 57, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Question 2");
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(15, 176, 75, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Answer:");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(15, 216, 57, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Question 3");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(15, 280, 75, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Answer:");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(15, 320, 57, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Question 4");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(15, 380, 75, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Answer:");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(15, 420, 57, 17);

        pergunta1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta1.setForeground(new java.awt.Color(102, 102, 102));
        pergunta1.setBorder(null);
        kGradientPanel1.add(pergunta1);
        pergunta1.setBounds(108, 75, 518, 22);

        pergunta2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta2.setForeground(new java.awt.Color(102, 102, 102));
        pergunta2.setBorder(null);
        kGradientPanel1.add(pergunta2);
        pergunta2.setBounds(108, 172, 518, 22);

        pergunta3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta3.setForeground(new java.awt.Color(102, 102, 102));
        pergunta3.setBorder(null);
        kGradientPanel1.add(pergunta3);
        pergunta3.setBounds(108, 376, 518, 22);

        pergunta4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta4.setForeground(new java.awt.Color(102, 102, 102));
        pergunta4.setBorder(null);
        kGradientPanel1.add(pergunta4);
        pergunta4.setBounds(108, 276, 518, 22);

        resposta1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta1.setForeground(new java.awt.Color(51, 51, 51));
        resposta1.setBorder(null);
        kGradientPanel1.add(resposta1);
        resposta1.setBounds(108, 117, 518, 21);

        resposta2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta2.setForeground(new java.awt.Color(51, 51, 51));
        resposta2.setBorder(null);
        kGradientPanel1.add(resposta2);
        resposta2.setBounds(110, 420, 518, 21);

        resposta3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta3.setForeground(new java.awt.Color(51, 51, 51));
        resposta3.setBorder(null);
        kGradientPanel1.add(resposta3);
        resposta3.setBounds(108, 216, 518, 21);

        resposta4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta4.setForeground(new java.awt.Color(51, 51, 51));
        resposta4.setBorder(null);
        kGradientPanel1.add(resposta4);
        resposta4.setBounds(108, 320, 518, 21);

        jButton1.setText("Proximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1);
        jButton1.setBounds(550, 500, 75, 22);

        painel1.add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 710, 570);

        slide.add(painel1, "card2");

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(215, 215, 215));
        kGradientPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Questions for the Interviewed");
        kGradientPanel2.add(jLabel2);
        jLabel2.setBounds(15, 16, 325, 32);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(403, 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        kGradientPanel2.add(jPanel5);
        jPanel5.setBounds(15, 54, 403, 3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Question 5");
        kGradientPanel2.add(jLabel11);
        jLabel11.setBounds(15, 79, 75, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Answer:");
        kGradientPanel2.add(jLabel12);
        jLabel12.setBounds(15, 120, 57, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Question 6");
        kGradientPanel2.add(jLabel13);
        jLabel13.setBounds(15, 176, 75, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Answer:");
        kGradientPanel2.add(jLabel14);
        jLabel14.setBounds(15, 216, 57, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Question 7");
        kGradientPanel2.add(jLabel15);
        jLabel15.setBounds(15, 280, 75, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Answer:");
        kGradientPanel2.add(jLabel16);
        jLabel16.setBounds(15, 320, 57, 17);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Question 8");
        kGradientPanel2.add(jLabel17);
        jLabel17.setBounds(15, 380, 75, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Answer:");
        kGradientPanel2.add(jLabel18);
        jLabel18.setBounds(15, 420, 57, 17);

        pergunta5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta5.setForeground(new java.awt.Color(102, 102, 102));
        pergunta5.setBorder(null);
        kGradientPanel2.add(pergunta5);
        pergunta5.setBounds(108, 75, 518, 22);

        pergunta6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta6.setForeground(new java.awt.Color(102, 102, 102));
        pergunta6.setBorder(null);
        kGradientPanel2.add(pergunta6);
        pergunta6.setBounds(108, 172, 518, 22);

        pergunta8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta8.setForeground(new java.awt.Color(102, 102, 102));
        pergunta8.setBorder(null);
        kGradientPanel2.add(pergunta8);
        pergunta8.setBounds(108, 376, 518, 22);

        pergunta7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        pergunta7.setForeground(new java.awt.Color(102, 102, 102));
        pergunta7.setBorder(null);
        kGradientPanel2.add(pergunta7);
        pergunta7.setBounds(108, 276, 518, 22);

        resposta5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta5.setForeground(new java.awt.Color(51, 51, 51));
        resposta5.setBorder(null);
        kGradientPanel2.add(resposta5);
        resposta5.setBounds(108, 117, 518, 21);

        resposta8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta8.setForeground(new java.awt.Color(51, 51, 51));
        resposta8.setBorder(null);
        kGradientPanel2.add(resposta8);
        resposta8.setBounds(110, 420, 518, 21);

        resposta6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta6.setForeground(new java.awt.Color(51, 51, 51));
        resposta6.setBorder(null);
        kGradientPanel2.add(resposta6);
        resposta6.setBounds(108, 216, 518, 21);

        resposta7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        resposta7.setForeground(new java.awt.Color(51, 51, 51));
        resposta7.setBorder(null);
        kGradientPanel2.add(resposta7);
        resposta7.setBounds(108, 320, 518, 21);

        jButton6.setText("Proximo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton6);
        jButton6.setBounds(570, 500, 75, 22);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton2);
        jButton2.setBounds(480, 500, 72, 22);

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        slide.add(painel2, "card3");

        jButton4.setText("Voltar");

        jButton5.setText("Cadastrar Questionário");

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel3Layout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(39, 39, 39))
        );

        slide.add(painel3, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        slide.nextPanel(30, painel2, slide.right);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        slide.nextPanel(30, painel1, slide.left);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JTextField pergunta1;
    private javax.swing.JTextField pergunta2;
    private javax.swing.JTextField pergunta3;
    private javax.swing.JTextField pergunta4;
    private javax.swing.JTextField pergunta5;
    private javax.swing.JTextField pergunta6;
    private javax.swing.JTextField pergunta7;
    private javax.swing.JTextField pergunta8;
    private javax.swing.JTextField resposta1;
    private javax.swing.JTextField resposta2;
    private javax.swing.JTextField resposta3;
    private javax.swing.JTextField resposta4;
    private javax.swing.JTextField resposta5;
    private javax.swing.JTextField resposta6;
    private javax.swing.JTextField resposta7;
    private javax.swing.JTextField resposta8;
    private diu.swe.habib.JPanelSlider.JPanelSlider slide;
    // End of variables declaration//GEN-END:variables
}
